heavens_reverends/appointments/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, IntegerField
from wtforms_components import TimeField
from wtforms_components.fields.html5 import DateTimeLocalField, DateTimeField
from wtforms.validators import DataRequired, Optional
# from wtforms_components.widgets import DateTimeInput

class AppointmentForm(FlaskForm):
    appointment_type = SelectField(label='Appointment Type',choices=['Wedding Ceremony','Something Else'], validators=[DataRequired()])
    submit = SubmitField('Go')

class WeddingAppointmentForm(FlaskForm):
    first_name = StringField('First Name: ', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    spouse_first_name = StringField('Spouse First Name', validators=[DataRequired()])
    spouse_last_name = StringField('Spouse Last Name', validators=[DataRequired()])
    appointment_date = DateTimeLocalField('Appointment Date', format='%Y-%m-%dT%H:%M', validators=[DataRequired()])
    submit = SubmitField('Book')

# Could maybe combine this with above
class AppointmentUpdateForm(FlaskForm):
    first_name = StringField('First Name: ', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    appointment_type = TextAreaField('Appointment Type', validators=[DataRequired()])
    appointment_date = DateTimeField('Appointment Date', format='%m/%d/%y')
    submit = SubmitField('Update')
    cancel = SubmitField('Cancel')

class WeddingAppointmentUpdateForm(FlaskForm):
    first_name = StringField('First Name: ', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    spouse_first_name = StringField('Spouse First Name', validators=[DataRequired()])
    spouse_last_name = StringField('Spouse Last Name', validators=[DataRequired()])
    appointment_date = DateTimeLocalField('Appointment Date', format='%Y-%m-%dT%H:%M', validators=[DataRequired()])
    submit = SubmitField(label='Update')

class CustomizeWeddingForm(FlaskForm):
    theme = SelectField('Theme', choices=[('wwe','WWE'),('indycar','IndyCar'),('brass-bull','Brass Bull')],validators=[]) # ,validators=[DataRequired()])
    length_minutes = IntegerField('Time (Minutes)',validators=[Optional()])
    # venue = StringField('Venue',validators=[Optional()]) # need to create venue table with venue_id
    religious_verses = StringField('Religious Verses',validators=[Optional()])
    # attire
    # dual_reverend
    submit = SubmitField('Submit')

heavens_reverends/books/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms_components.fields.html5 import DateField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
    title = StringField('HR Book Title', validators=[DataRequired()])
    author = StringField('HR Book Author', validators=[DataRequired()])
    book_content = TextAreaField('HR Book Content', validators=[DataRequired()])
    publish_date = DateField('Publish Date', format='%Y-%m-%d', validators=[DataRequired()])
    submit = SubmitField('Publish')

# Could maybe combine this with above
class BookUpdateForm(FlaskForm):
    title = StringField('HR Post Title', validators=[DataRequired()])
    author = StringField('HR Book Author', validators=[DataRequired()])
    book_content = TextAreaField('HR Book Content', validators=[DataRequired()])
    publish_date = DateField('Publish Date', format='%Y-%m-%d', validators=[DataRequired()])
    submit = SubmitField('Update')
    cancel = SubmitField('Cancel')

heavens_reverends/appointments/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from heavens_reverends import db
from heavens_reverends.models import Appointment
from heavens_reverends.appointments.forms import (AppointmentForm, AppointmentUpdateForm, WeddingAppointmentForm, WeddingAppointmentUpdateForm,
                                                 CustomizeWeddingForm)
from datetime import datetime, timedelta

appointments = Blueprint('appointments',__name__)

@appointments.route('/appointments', methods=['GET','POST'])
@login_required
def book_appointment():
    form = AppointmentForm()

    if form.validate_on_submit():
        appointment_type = form.appointment_type.data
        session['appointment_type'] = appointment_type
        return redirect(url_for('book_'+appointment_type+'_appointment'))

    return render_template('appointments.html', form=form)


# CREATE
@appointments.route('/appointments/wedding',methods=['GET','POST'])
@login_required
def book_wedding_appointment():
    form = WeddingAppointmentForm()
    appointment_type = 'wedding'

    if form.validate_on_submit():
        appointment = Appointment(
                        appointment_type=appointment_type,
                        appointment_date=form.appointment_date.data,
                        first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        spouse_first_name=form.spouse_first_name.data,
                        spouse_last_name=form.spouse_last_name.data,
                        user_id=current_user.id)
        db.session.add(appointment)
        db.session.commit()
        flash('Wedding Appointment Booked!')
        # return redirect(url_for('appointments.user_appointments'))
        return redirect(url_for('appointments.customize_wedding',appointment_id=appointment.id))


    return render_template('book_wedding_appointment.html',form=form)

# READ
@appointments.route('/appointments/myappointments',methods=['GET','POST'])
@login_required
def user_appointments():
    appointments = Appointment.query.filter_by(user_id=current_user.id)
    return render_template('user_appointments.html',appointments=appointments)

# UPDATE
@appointments.route('/appointments/myappointments/<int:appointment_id>/update',methods=['GET','POST'])
@login_required
def update_wedding_appointment(appointment_id):
    appointment = Appointment.query.get_or_404(appointment_id)
    if appointment.user_id != current_user.id:
        abort(403)

    form = WeddingAppointmentUpdateForm()

    if form.validate_on_submit():
        appointment.first_name = form.first_name.data
        appointment.last_name = form.last_name.data
        appointment.spouse_first_name = form.spouse_first_name.data
        appointment.spouse_last_name = form.spouse_last_name.data
        appointment.appointment_date = form.appointment_date.data
        appointment.appointment_type = 'wedding'
        db.session.commit()
        flash('Appointment Updated')
        return redirect(url_for('appointments.user_appointments'))

    elif request.method == 'GET':
        form.first_name.data = appointment.first_name
        form.last_name.data = appointment.last_name
        form.spouse_first_name.data = appointment.spouse_first_name
        form.spouse_last_name.data = appointment.spouse_last_name
        form.appointment_date.data = appointment.appointment_date

    return render_template('book_wedding_appointment.html',title='Updating',form=form)


@appointments.route('/appointments/myappointments/<int:appointment_id>/customize',methods=['GET','POST'])
@login_required
def customize_wedding(appointment_id):
    appointment = Appointment.query.get_or_404(appointment_id)
    if appointment.user_id != current_user.id:
        abort(403)

    form = CustomizeWeddingForm()
    if form.validate_on_submit():
        has_update_data = (appointment.theme != form.theme.data \
                              or appointment.length_minutes != int(form.length_minutes.data)) \
                              or appointment.religious_verses != form.religious_verses.data \
                          and (form.theme.data is not None
                              or form.length_minutes.data is not None
                              or form.religious_verses.data is not None)
        if has_update_data:
            appointment.theme = form.theme.data
            appointment.length_minutes = form.length_minutes.data
            appointment.religious_verses = form.religious_verses.data
            db.session.commit()
            flash('Wedding Customized!')

        return redirect(url_for('appointments.user_appointments'))
    elif request.method == 'GET':
        form.theme.data = appointment.theme
        form.length_minutes.data = appointment.length_minutes
        form.religious_verses.data = appointment.religious_verses


    return render_template('customize_wedding.html',title='Customize Wedding',form=form)



#DELETE
@appointments.route('/appointments/myappointments/<int:appointment_id>/delete',methods=['GET','POST'])
@login_required
def delete_wedding_appointment(appointment_id):
    appointment = Appointment.query.get_or_404(appointment_id)
    if appointment.user_id != current_user.id:
        abort(403)

    db.session.delete(appointment)
    db.session.commit()
    flash('Appointment Deleted')
    return redirect(url_for('appointments.user_appointments'))

heavens_reverends/books/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint
from flask_login import current_user,login_required
from heavens_reverends import db
from heavens_reverends.models import Book
from heavens_reverends.books.forms import BookForm, BookUpdateForm

books = Blueprint('books',__name__)

# CREATE
@books.route('/write',methods=['GET','POST'])
@login_required
def add_book():
    form = BookForm()

    if form.validate_on_submit():
        book = Book(title=form.title.data,
                    author=form.author.data,
                    content=form.book_content.data,
                    publish_date=form.publish_date.data
                    )
        db.session.add(book)
        db.session.commit()
        flash('Book Added')
        return redirect(url_for('core.books'))

    return render_template('add_book.html',form=form)
# READ
@books.route('/books/<int:book_id>')
def book(book_id):
    book = Book.query.get_or_404(book_id)
    return render_template('book.html',title=book.title,
                                       author=book.author,
                                       contents=book.content,
                                       publish_date=book.publish_date,
                                       book=book)

# UPDATE
@books.route('/<int:book_id>/update',methods=['GET','POST'])
@login_required
def update_book(post_id):
    book = Book.query.get_or_404(post_id)
    if book.author != current_user:
        abort(403)

    form = BookUpdateForm()

    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.autor.data
        if form.submit.data:
            db.session.commit()
            flash('Book Updated')
        return redirect(url_for('books.book',book_id=book.id))
    elif request.method == 'GET':
        form.title.data = book.title
        form.contents.data = book.content

    return render_template('update_book.html',title='Updating',form=form)

#DELETE
@books.route('/books/<int:book_id>/delete',methods=['GET','POST'])
@login_required
def delete_book(book_id):
    book = Book.query.get_or_404(book_id)
    # if book.author != current_user:
    #     abort(403)

    db.session.delete(book)
    db.session.commit()
    flash('Book Deleted')
    return redirect(url_for('core.books'))

heavens_reverends/core/views.py
from flask import render_template, request, Blueprint
from heavens_reverends.models import Post, Book

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.created_at.desc()).paginate(page=page,per_page=5)

    return render_template('index.html', posts=posts)

@core.route('/info')
def info():
    return render_template('info.html')

@core.route('/books')
def books():
    page = request.args.get('page',1,type=int)
    books = Book.query.order_by(Book.publish_date.desc()).paginate(page=page,per_page=5)

    return render_template('books.html', books=books)

heavens_reverends/posts/views.py
# blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from heavens_reverends import db
from heavens_reverends.models import Post
from heavens_reverends.posts.forms import PostForm, PostUpdateForm

posts = Blueprint('posts',__name__)

# CREATE
@posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    text=form.text.data,
                    user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)
# READ
@posts.route('/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.title
                          ,created_at=post.created_at,post=post)

# UPDATE
@posts.route('/<int:post_id>/update',methods=['GET','POST'])
@login_required
def update(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostUpdateForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        if form.submit.data:
            db.session.commit()
            flash('Post Updated')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text

    return render_template('create_post.html',title='Updating',form=form)

#DELETE
@posts.route('/<int:post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted')
    return redirect(url_for('core.index'))

heavens_reverends/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from heavens_reverends import db
from heavens_reverends.models import User, Post
from heavens_reverends.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from heavens_reverends.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                flash('Login Successful')

                next = request.args.get('next')

                if next == None or not next[0] == '/':
                    next = url_for('core.index')

                    return redirect(next)
            else:
                error_message = 'Invalid Password'
                return render_template('login.html', form=form, error_message=error_message)
        else:
            error_message = 'Username does not exist.'
            return render_template('login.html', form=form, error_message=error_message)

    return render_template('login.html', form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

#account (update UserForm)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)
# user's list of blog posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.created_at.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

heavens_reverends/templates/appointments.html
{% extends "base.html" %}
{% block content %}
<div>
  {% for c in form.appointment_type.choices %}
  <!-- <a href="{{url_for('appointments.book_wedding_appointment')}}"> -->
    <button class='jumbotron' type="button" name="button" align="center">
        {{c}}
    </button>
  <!-- </a> -->
  {% endfor %}<br>
  <button type="button" name="button">
    Go
  </button>
</div>


<!-- Modal for Pop Up-->
{# https://getbootstrap.com/docs/4.1/components/modal/ #}
{# Notice how the link with the id to the button above! #}
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post Pop up Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

heavens_reverends/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title>Heaven's Reverends</title>
    <style media="screen">
      .text-center-smashed {
        align: center;
        padding: 10px;
        text-align: center;
        margin: 0px;
        margin-top: 5px;
        border-radius: 15px;
        color: #000000;
      }
      .posts-list {
          border-radius: 20px;
          /* width: 670px; */
          /* margin-left: -5px; */
      }
      .rounded {
        border-radius: 20px;
      }
      .bg-red {
          background-color: red;
      }
      .bg-gold {
          /* background-color: #FFDD4D; */
          background-color: #d4af37;
          /* border: solid black; */
      }
      .bg-black {
          background-color: #141414;
          /* background-color: #1B1B1B */
      }
      .bg-white {
          background-color: #000000;
      }
      .bg-dark-grey {
          background-color: #565656;
      }
      .bg-light-grey {
          background-color: #F5F5F5;
      }
      .jumbo-head {
        /* width: 740px;
        margin-left: -40px; */
        margin-top: 20px;
        margin-bottom: 15px;
      }
      .bg-logo {
        background-image: url('static/profile_pics/hr_logo.jpg');
        background-repeat: no-repeat;
        height: 670px;
        width: 550px;
      }.bg-drake {
        background-image: url('static/profile_pics/revdrake.jpg');
        background-repeat: no-repeat;
        height:395px;
        width: 355px;
        background-position: 0px -50px;
        background-size: 350px 450px;
      }
      .bg-ryan {
        background-image: url('static/profile_pics/revryan.png');
        background-repeat: no-repeat;
        height:395px;
        width: 355px;
        background-size: 350px 390px;
      }
      .bg-chris {
        background-image: url('static/profile_pics/revchris.png');
        background-repeat: no-repeat;
        height:395px;
        width: 355px;
        background-size: 350px 390px;
      }
      .bg-yosh {
        background-image: url('static/profile_pics/revyosh.jpg');
        background-repeat: no-repeat;
        height:395px;
        width: 355px;
        background-size: 350px 390px;
      }
      .bg-logo2 {
        background-image: url('static/profile_pics/hr_logo.jpg');
        height: 205px;
        width: 175px;
        background-repeat: no-repeat;
        background-size: 170px 200px;
      }
      .img-negative {
       -webkit-filter: invert(1);
       filter: invert(1);
      }
      .logo-fit {
        margin-top: 3px;
        margin-left: 3px;
        object-fit: scale-down;
        height: 70px;
        width: 70px;
      }
      .shadow {
        box-shadow:3px 3px 3px 3px #d4af37;
        border: #d4af37;
      }
      .white-text {
        color: white;
      }
      .black-text {
        color: #141414;
      }
      .gold-text {
        color: #d4af37;
      }
      .light-grey-text {
          color: #F5F5F5;
      }
      .gold-border {
        border: solid #d4af37;
      }
      .cursive {
        font-family: cursive;
      }
    </style>
  </head>
  <body class="bg-black">
  <!-- <body class='bg-logo'> -->
      <ul class='nav bg-gold black-text'>
      <!-- <ul class='navbar bg-gold'> -->
        <!-- <li> <img src="'static/profile_pics/hr_logo.jpg'" height=300px></li> -->
        <a class="black-text" href="{{url_for('core.index')}}">
          <li class='nav-link black-text bg-gold btn btn-outline-dark gold-border'>
            Home
          </li>
        </a>
        <a class="black-text" href="{{url_for('core.info')}}">
          <li class='nav-link bg-gold btn black-text btn-outline-dark gold-border'>
            About
          </li>
        </a>
        {% if current_user.is_authenticated %}
        <!-- <a class="black-text" href="{{url_for('core.books')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Books
          </li>
        </a> -->
        <a class="black-text" href="{{url_for('appointments.book_wedding_appointment')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Appointments
          </li>
        </a>
        <a class="black-text" href="{{url_for('users.account')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Account
          </li>
        </a>
          {% if current_user.username in ['revdrake','revryan'] %}
          <a class="black-text" href="{{url_for('books.add_book')}}">
            <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
              Write Book
            </li>
          </a>
          {% endif %}
        <!-- <a class="black-text"href="{{url_for('posts.create_post')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Create Post
          </li>
        </a> -->
        <a class="black-text"href="{{url_for('users.logout')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Log Out
          </li>
        </a>
        {% else %}
        <a class="black-text"href="{{url_for('users.login')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Log In
          </li>
        </a>
        <a class="black-text" href="{{url_for('users.register')}}">
          <li class='nav-link bg-gold btn btn-outline-dark black-text gold-border'>
            Register
          </li>
        </a>
        {% endif %}
      </ul>
      <div class="container" style="text-align: center;">
        {% block content %}

        {% endblock %}
      </div>
    </div>
  </body>
</html>

heavens_reverends/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
    {{form.hidden_tag()}}

    <div class="form-group text-center-smashed">
      {{form.title.label(class="form-control-label")}}
      {{form.title(class="form-control form-control-lg")}}
    </div>
    <div class="form-group text-center-smashed">
      {{form.text.label(class="form-control-label")}}
      {{form.text(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-primary gold-border white-text")}}
      {% if form.cancel %}
        {{form.cancel(class="btn btn-outline-danger" if form.cancel)}}
      {% endif %}
    </div>
  </form>
</div>
{% endblock %}

heavens_reverends/templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
  </h2>
  <h3>Published: {{ post.created_at.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('posts.update', post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_post">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_post">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

heavens_reverends/templates/user_appointments.html
{% extends "base.html" %}
{% block content %}
{% for appt in appointments %}
<div>
  <div class="jumbotron jumbo-head text-center-smashed bg-black gold-border gold-text cursive">
    <h1 align="center">
      Wedding Consultation<br>
      {{appt.first_name+' '+appt.last_name+' & '+appt.spouse_first_name+' '+appt.spouse_last_name}}<br>
      {{appt.appointment_date.strftime(format='%-m/%-d/%Y %-I:%M %p')}}<br>
      {% if appt.theme %}
        Theme: {{appt.theme}} <br>
      {% endif %}
      {% if appt.length_minutes %}
        {{appt.length_minutes}} minutes<br>
      {% endif %}
      {% if appt.religious_verses %}
        {{appt.religious_verses}}<br>
      {% endif %}
      <div>
        <a class="btn btn-outline-secondary light-grey-text gold-border" href="{{ url_for('appointments.customize_wedding', appointment_id=appt.id) }}">Customize Wedding</a>
        <a class="btn btn-outline-info" href="{{ url_for('appointments.update_wedding_appointment', appointment_id=appt.id) }}">Update Appointment</a>
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#del_wedding_appointment">Cancel Appointment</button>
      </div>
    </h1>
  </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="del_wedding_appointment">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Appointment Pop up Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to cancel your appointment?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{ url_for('appointments.delete_wedding_appointment', appointment_id=appt.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}